#!/bin/sh
bspc rule -r "*"

# Autostart
~/.config/polybar/launch.sh &
sxhkd 

# Monitors
bspc monitor HDMI-A-1 -a 1 2 3 4 5 6 7
bspc monitor HDMI-A-0 -a 8 9 10

# Global Settings
bspc config automatic_scheme alternate 
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true

bspc config normal_border_color "#6a67ac"
bspc config active_border_color "#d75fd7"
bspc config focused_border_color "#d75fd7"
bspc config urgent_border_color "#666"

# Padding and Borders
bspc config top_padding 28
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 1
bspc config window_gap 10

# Rules (ugh...)
bspc rule -a Quake state=fullscreen
bspc rule -a osu! state=fullscreen
bspc rule -a Steam state=fullscreen
